/** Canonical Smart Manager permission catalog shared with the API runtime. */
export const SMART_MANAGER_PERMISSION_KEYS = [
  "company.view",
  "company.manage",
  "branch.view",
  "branch.manage",
  "unit.view",
  "unit.manage",
  "users.view",
  "users.manage",
  "roles.view",
  "roles.manage",
  "permissions.view",
  "permissions.manage",
  "kpi.view",
  "kpi.create",
  "kpi.update",
  "kpi.submit",
  "kpi.review",
  "kpi.approve",
  "redflag.view",
  "redflag.create",
  "redflag.update",
  "redflag.resolve",
  "dashboard.view",
  "dashboard.create",
  "dashboard.update",
  "dashboard.delete",
  "dashboard.share",
  "formula.view",
  "formula.create",
  "formula.update",
  "formula.publish",
  "action.view",
  "action.create",
  "action.update",
  "action.update-own",
  "action.manage",
  "action.approve",
  "action.close",
  "kpi.manage",
  "decision.view",
  "decision.create",
  "decision.approve",
  "meeting.view",
  "meeting.create",
  "meeting.update",
  "meeting.close",
  "alert.view",
  "alert.acknowledge",
  "alert.resolve",
  "report.view",
  "report.export",
  "ai.view",
  "ai.chat",
  "ai.analytics",
  "ai.recommendations",
  "integration.view",
  "integration.manage",
  "audit.view",
] as const;

export type SmartManagerPermission =
  (typeof SMART_MANAGER_PERMISSION_KEYS)[number];

export const SMART_MANAGER_PERMISSION_DEFINITIONS =
  SMART_MANAGER_PERMISSION_KEYS.map((key) => {
    const separator = key.lastIndexOf(".");
    return {
      key,
      resource: key.slice(0, separator),
      action: key.slice(separator + 1),
      description: key,
    };
  });

export const SMART_MANAGER_SYSTEM_ROLES = [
  "GROUP_CEO",
  "GROUP_COO",
  "PMO",
  "PMO_REVIEWER",
  "COMPANY_CEO",
  "PNL_OWNER",
  "SALES_MANAGER",
  "FINANCE_MANAGER",
  "HR_MANAGER",
  "OPERATIONS_MANAGER",
  "DATA_OWNER",
  "DATA_ENTRY",
  "KPI_REVIEWER",
  "TECHNICAL_ADMIN",
] as const;

export type SmartManagerSystemRole =
  (typeof SMART_MANAGER_SYSTEM_ROLES)[number];

const viewAll: readonly SmartManagerPermission[] =
  SMART_MANAGER_PERMISSION_KEYS.filter((key) => key.endsWith(".view"));
const companyManager: readonly SmartManagerPermission[] = [
  "company.view",
  "branch.view",
  "unit.view",
  "users.view",
  "users.manage",
  "roles.view",
  "kpi.view",
  "kpi.create",
  "kpi.update",
  "kpi.submit",
  "kpi.review",
  "kpi.approve",
  "dashboard.view",
  "dashboard.create",
  "dashboard.update",
  "dashboard.share",
  "formula.view",
  "formula.create",
  "formula.update",
  "formula.publish",
  "action.view",
  "action.create",
  "action.update",
  "action.approve",
  "action.close",
  "decision.view",
  "decision.create",
  "decision.approve",
  "meeting.view",
  "meeting.create",
  "meeting.update",
  "meeting.close",
  "alert.view",
  "alert.acknowledge",
  "alert.resolve",
  "report.view",
  "report.export",
  "ai.chat",
  "ai.analytics",
  "ai.recommendations",
  "audit.view",
  "redflag.view",
  "redflag.create",
  "redflag.update",
  "redflag.resolve",
];

/** Operational company administration intentionally excludes infrastructure and permission-catalog control. */
export const SMART_MANAGER_COMPANY_ADMIN_GRANTS: readonly SmartManagerPermission[] =
  [
    "company.view",
    "company.manage",
    "branch.view",
    "branch.manage",
    "unit.view",
    "unit.manage",
    "users.view",
    "users.manage",
    "roles.view",
    "roles.manage",
    "kpi.view",
    "kpi.create",
    "kpi.update",
    "kpi.submit",
    "kpi.review",
    "kpi.approve",
    "kpi.manage",
    "dashboard.view",
    "dashboard.create",
    "dashboard.update",
    "dashboard.delete",
    "dashboard.share",
    "formula.view",
    "formula.create",
    "formula.update",
    "formula.publish",
    "action.view",
    "action.create",
    "action.update",
    "action.manage",
    "action.approve",
    "action.close",
    "decision.view",
    "decision.create",
    "decision.approve",
    "meeting.view",
    "meeting.create",
    "meeting.update",
    "meeting.close",
    "alert.view",
    "alert.acknowledge",
    "alert.resolve",
    "report.view",
    "report.export",
    "audit.view",
    "redflag.view",
    "redflag.create",
    "redflag.update",
    "redflag.resolve",
    "ai.chat",
    "ai.analytics",
    "ai.recommendations",
  ];

/** Initial grants are intentionally least-privilege; custom roles remain data-driven. */
export const SMART_MANAGER_ROLE_GRANTS: Readonly<
  Record<SmartManagerSystemRole, readonly SmartManagerPermission[]>
> = {
  GROUP_CEO: SMART_MANAGER_PERMISSION_KEYS.filter(
    (key) => !key.startsWith("integration.") && !key.startsWith("permissions."),
  ),
  GROUP_COO: SMART_MANAGER_PERMISSION_KEYS.filter(
    (key) => !key.startsWith("integration.") && !key.startsWith("permissions."),
  ),
  PMO: [
    "company.view",
    "branch.view",
    "unit.view",
    "kpi.view",
    "kpi.review",
    "dashboard.view",
    "action.view",
    "action.update",
    "decision.view",
    "meeting.view",
    "meeting.create",
    "alert.view",
    "alert.acknowledge",
    "redflag.view",
    "redflag.create",
    "redflag.update",
    "report.view",
    "audit.view",
  ],
  PMO_REVIEWER: [
    "company.view",
    "branch.view",
    "unit.view",
    "kpi.view",
    "kpi.review",
    "dashboard.view",
    "action.view",
    "decision.view",
    "meeting.view",
    "alert.view",
    "redflag.view",
    "report.view",
  ],
  COMPANY_CEO: companyManager,
  PNL_OWNER: [
    "company.view",
    "kpi.view",
    "kpi.submit",
    "dashboard.view",
    "formula.view",
    "action.view",
    "decision.view",
    "meeting.view",
    "alert.view",
    "report.view",
    "ai.chat",
    "ai.analytics",
  ],
  SALES_MANAGER: [
    "company.view",
    "unit.view",
    "users.view",
    "kpi.view",
    "kpi.create",
    "kpi.update",
    "kpi.submit",
    "dashboard.view",
    "action.view",
    "action.create",
    "action.update",
    "alert.view",
    "alert.acknowledge",
    "report.view",
    "ai.chat",
    "ai.analytics",
    "ai.recommendations",
  ],
  FINANCE_MANAGER: [
    "company.view",
    "unit.view",
    "kpi.view",
    "kpi.create",
    "kpi.update",
    "kpi.submit",
    "dashboard.view",
    "action.view",
    "action.create",
    "action.update",
    "alert.view",
    "report.view",
    "ai.chat",
    "ai.analytics",
    "ai.recommendations",
  ],
  HR_MANAGER: [
    "company.view",
    "unit.view",
    "users.view",
    "kpi.view",
    "kpi.submit",
    "dashboard.view",
    "action.view",
    "alert.view",
    "report.view",
    "ai.chat",
    "ai.analytics",
  ],
  OPERATIONS_MANAGER: [
    "company.view",
    "branch.view",
    "unit.view",
    "kpi.view",
    "kpi.create",
    "kpi.update",
    "kpi.submit",
    "dashboard.view",
    "action.view",
    "action.create",
    "action.update",
    "action.approve",
    "alert.view",
    "alert.acknowledge",
    "alert.resolve",
    "redflag.view",
    "redflag.create",
    "redflag.update",
    "redflag.resolve",
    "report.view",
    "ai.chat",
    "ai.analytics",
    "ai.recommendations",
  ],
  DATA_OWNER: [
    "company.view",
    "unit.view",
    "users.view",
    "kpi.view",
    "kpi.create",
    "kpi.update",
    "kpi.submit",
    "dashboard.view",
    "formula.view",
    "formula.create",
    "formula.update",
    "redflag.view",
    "report.view",
    "ai.chat",
    "ai.analytics",
  ],
  DATA_ENTRY: [
    "company.view",
    "kpi.view",
    "kpi.submit",
    "action.view",
    "alert.view",
  ],
  KPI_REVIEWER: [
    "company.view",
    "unit.view",
    "kpi.view",
    "kpi.review",
    "kpi.approve",
    "dashboard.view",
    "formula.view",
    "redflag.view",
    "redflag.update",
    "redflag.resolve",
    "report.view",
  ],
  TECHNICAL_ADMIN: [
    "users.view",
    "roles.view",
    "roles.manage",
    "permissions.view",
    "permissions.manage",
    "integration.view",
    "integration.manage",
    "audit.view",
  ],
};

export const SMART_MANAGER_ROLE_SCOPE: Readonly<
  Record<
    SmartManagerSystemRole,
    "holding" | "company" | "businessUnit" | "own" | "assigned" | "domain"
  >
> = {
  GROUP_CEO: "holding",
  GROUP_COO: "holding",
  PMO: "holding",
  PMO_REVIEWER: "holding",
  COMPANY_CEO: "company",
  PNL_OWNER: "company",
  SALES_MANAGER: "domain",
  FINANCE_MANAGER: "domain",
  HR_MANAGER: "domain",
  OPERATIONS_MANAGER: "company",
  DATA_OWNER: "company",
  DATA_ENTRY: "assigned",
  KPI_REVIEWER: "company",
  TECHNICAL_ADMIN: "own",
};

export const SMART_MANAGER_ROLE_DOMAINS: Partial<
  Record<SmartManagerSystemRole, string>
> = {
  SALES_MANAGER: "sales",
  FINANCE_MANAGER: "finance",
  HR_MANAGER: "hr",
};
